projects:
  groupChatApiMicroservice:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/types/amplify.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/amplify.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 5ytfjd2yqja6talzouq7wekgzq
        maxDepth: 2
extensions:
  amplify:
    version: 3
